@startuml
!NEW_C4_STYLE=1

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title System Context Diagram for NL-to-SPARQL system

Person(user, "User", "Inputs NL question or SPARQL query")

System(api, "API Application", "Processes NL question or SPARQL query to output corresponding SPARQL query or NL question respectively")

System_Ext(dbpedia, "DBPedia", "External sparql endpoint containing triples")
System_Ext(llm, "LLM", "Hactar used as a syntax generation engine")

Rel(user, api, "Queries system via HTTP")
Rel(api, dbpedia, "Fetches schema, sample triples, and executes final queries")
Rel(api, llm, "Sends few-shot prompts and receives generated SPARQL query")

SHOW_LEGEND()
@enduml
